### ISSUE TITLE
create/write down concepts for documentation

### ISSUE THREAD

**Issue by fionatiefenbacher** [FHNW-IVGI/Geoharvester#10]
As a deliverable for the AP1, following concepts need to be documented:

- [x] Architecture
- [x] Data modelling - check scraper and the implications for the project
- [x] Interface ideas based on Personas

**Comment by FStriewski** [comment]
Closing this for now - the schema needs docuentation, but we can do that once we have a define version (scraper fields + our own fields from the NLP preprocessing)
