### ISSUE TITLE
Some source are not returning results

### ISSUE THREAD

**Issue by p1d1d1** [FHNW-IVGI/Geoharvester#100]
ST_ZH, ST_BE, SOSM, ASIT return "Keine Treffer ..."

**Comment by FStriewski** [comment]
Yes, I noticed this too this morning. The issue is that  the new data from the scraper run was not saved to the github and thus not ingested into redis. Once the current run is finished, the new data should be there.

**Comment by FStriewski** [comment]
Data for SOSM, AGIT and ST_ZH is now available. ST_BE did not results during scraping and wasn't processed in the latest run.
