### ISSUE TITLE
Table page is not updated after a search

### ISSUE THREAD

**Issue by carobro** [FHNW-IVGI/Geoharvester#107]
**Problem:**
I displayed all the data records of a provider (Basel-Land). So that I can see all data records, I clicked through the pages. On page 9 I wanted to search for a term that I know exists ("grenze"). I got back an empty table.
I had to go back to page 1 to see the updated table (see Image 1 and 2)

Image1: 
![image](https://github.com/FHNW-IVGI/Geoharvester/assets/38653703/4bf90585-f3b7-4676-bdf1-9934542a41e1)

Image2:
![image](https://github.com/FHNW-IVGI/Geoharvester/assets/38653703/b20e33fb-d275-487e-a8fd-98a5fe7d7dd0)

**Expectation:**
I would have expected the table to jump back to page 1 after i search for something

**Comment by FStriewski** [comment]
Is fixed and will be rolled out with the next update

**Comment by FStriewski** [comment]
Fixed in https://github.com/FHNW-IVGI/Geoharvester/pull/118
