### ISSUE TITLE
"Service in mapgeo öffnen" not working for BUND

### ISSUE THREAD

**Issue by p1d1d1** [FHNW-IVGI/Geoharvester#115]
The link "Service in mapgeo öffnen" is not working for the provider BUND.
The issue is due to a double question mark between service URL and layer name:

https://map.geo.admin.ch/?bgLayer=ch.swisstopo.pixelkarte-grau&layers=WMS||Feuchtflächenpotential Agrarland||https://wms.geo.admin.ch/**??**||ch.agroscope.feuchtflaechenpotential-kulturlandschaft||1.3.0

Working URL:
https://map.geo.admin.ch/?bgLayer=ch.swisstopo.pixelkarte-grau&layers=WMS||Feuchtflächenpotential Agrarland||https://wms.geo.admin.ch/?||ch.agroscope.feuchtflaechenpotential-kulturlandschaft||1.3.0

**Comment by p1d1d1** [comment]
@FStriewski could you please have a look at this with high prio? thanks

**Comment by FStriewski** [comment]
Fixed in https://github.com/FHNW-IVGI/Geoharvester/pull/118
