### ISSUE TITLE
WMS/WFS not working for QGIS

### ISSUE THREAD

**Issue by sfkeller** [FHNW-IVGI/Geoharvester#116]
Seems to me that the file (.qlr) which downlods when clicking "FOR QGIS" is not working in QGIS for any(!) WMS/WFS in the list from GeoHarvester.

The reason probably is in the datasource url in the .qlr file. The url is only the domain, but it should be the WMS/WFS base url.

So for example the .qlr for "Gemeindefeuerwehren (186.1)" currently contains url='https://maps.zh.ch/' => but correct is  url='https://maps.zh.ch/wfs/OGDZHWFS'.

Current (not working, wrong "url="):
```
<datasource> pagingEnabled='true' preferCoordinatesForWfsT11='false' restrictToRequestBBOX='1' srsname='EPSG:2056' typename='ms:ogd-0186_gvz_fw_gemeinden_f' url='https://maps.zh.ch/' version='auto'</datasource>
```
Working ("url=" corrected by me):
```
<datasource> pagingEnabled='true' preferCoordinatesForWfsT11='false' restrictToRequestBBOX='1' srsname='EPSG:2056' typename='ms:ogd-0186_gvz_fw_gemeinden_f' url='https://maps.zh.ch/wfs/OGDZHWFS' version='auto'</datasource>
```

**Comment by sfkeller** [comment]
Funktioniert immer noch nicht: Zum Reproduzieren 
- Suche nach "TBA Baustellen Kantonsstrassen" auf Geoharvester
- Klick auf Zeile. => Details klappen auf
- Klick auf "FOR QGIS". => Download von "TBA Baustellen auf Kantonsstrassen (OGD) (28.2).qlr".

Im "TBA Baustellen auf Kantonsstrassen (OGD) (28.2).qlr" ist "url='https://maps.zh.ch/'". Richtig wäre "url='https://maps.zh.ch/wfs/TbaBaustellenZHWFS'".

**Comment by FStriewski** [comment]
Fixed in https://github.com/FHNW-IVGI/Geoharvester/pull/120

Note that this feature reads the url from "endpoint". If this url is not specified correctly, the export will still fail. 
![qgis_export](https://github.com/user-attachments/assets/c96dfb39-490b-459c-bfa3-e4650bf507d8)

We catch missing or NaN values and lock the export buttons in such a case.
