### ISSUE TITLE
Evaluate / implement Redis geo-filters functionality

### ISSUE THREAD

**Issue by FStriewski** [FHNW-IVGI/Geoharvester#13]
### User Story:
As a user I want to find data based on its location.

### Description:
See Redis documentation on geo filters here:
https://redis.io/docs/stack/search/reference/query_syntax/ and
https://redis.com/redis-best-practices/indexing-patterns/geospatial/

The schema needs adjustments to become queryable for geo search. Also note that we have fields for both lat lon (center) as well as the bbox in the data, which might need to be used for topological checks.

**Comment by davidoesch** [comment]
If there is a need go a specific change in the output csv : state the format /Schema needed so we can work on this on our side

**Comment by FStriewski** [comment]
As discussed with Pasquale on 20/02/23, such functionality is not desired for the moment. Other features are more important.

**Comment by FStriewski** [comment]
As discussed with Pasquale on 20/02/23, such functionality is not desired for the moment. Other features are more important.

**Comment by FStriewski** [comment]
As discussed with Pasquale on 20/02/23, such functionality is not desired for the moment. Other features are more important.
