### ISSUE TITLE
[Fronted] Refine data export to Qgis and ArcGIS 

### ISSUE THREAD

**Issue by FStriewski** [FHNW-IVGI/Geoharvester#46]
### Description
Basic functionality was implemented in https://github.com/FHNW-IVGI/Geoharvester/pull/44 following the example (templates and code) from the Geoharvester_poc of David. During testing we noticed that the export seems to depend on the layer or service provider - for some the export succeeds for others the GIS drops a generic error message and aborts the import. This needs further testing and refinement so that we get more stable results.

### Considerations:
- Discuss with David
- Try to identify the source(s) of error or the differences in services that create the issue(s)

**Comment by fionatiefenbacher** [comment]
- [ ]  include correct KBS from service source

**Comment by ukaelin** [comment]
QGIS .qlr for WFS-Services for Canton BE do not work.

The .qlr has only the url https://www.geoservice.apps.be.ch in it. 
It would work if the url shown in the Geoharvester in "Endpoint" is used. For example: https://www.geoservice.apps.be.ch/geoservice3/services/a42geo/of_inlandwaters01_de_ms_wfs/MapServer/WFSServer?

**Comment by FStriewski** [comment]
Fixed in https://github.com/FHNW-IVGI/Geoharvester/pull/120. Note that if the endpoint url is not defined correctly, the export will still fail. We catch missing and NaN values for the URL and lock the  export buttons in that case.
