### ISSUE TITLE
[Backend, Frontend] Results ranking with filter

### ISSUE THREAD

**Issue by eliaferrari** [FHNW-IVGI/Geoharvester#52]
**Description**

The implemented ranking function is applied only if no filter (service / provider) is set.
The results seem to have a random order if a filter is set.
The issue could lie in the API getData function.
#28 

Without filters:
![Nofilter](https://github.com/FHNW-IVGI/Geoharvester/assets/39693711/e4facd8d-f3e2-4753-ad4c-376a1f1d2401)

With filter:
![filter](https://github.com/FHNW-IVGI/Geoharvester/assets/39693711/9792f8ea-ac21-44cb-8f10-9548da2780bb)

**Comment by eliaferrari** [comment]
@fionatiefenbacher and I found out that the problem lies on the browser.
Firefox works while chrome resort the results in reverse.
More information will follow.

**Comment by FStriewski** [comment]
With the latest changes introduced bythe pagination branch this seems to be no longer an issue. I`ve tried to replicate the error with the example provided, FF and Chrome are consistent and display "Entwässerungsgebiete" as top result.

Could you give it another check with the deployed version (http://3.76.227.122/) and if fixed, close this issue? @eliaferrari

**Comment by eliaferrari** [comment]
I've done some testing with both browsers and they seems to have the same behavior.
If you apply a filter the first time (without buffer) you have to press again "suchen" to obtain the right results. @FStriewski 
![First search](https://github.com/FHNW-IVGI/Geoharvester/assets/39693711/2fa1c24a-d328-4e7d-842c-693e1819d29f)
![Apply the filter for a canton](https://github.com/FHNW-IVGI/Geoharvester/assets/39693711/a7a160ae-6f10-46bb-9a44-57467096eea0)
![Pressed again the search botton](https://github.com/FHNW-IVGI/Geoharvester/assets/39693711/4d89b9e0-4b52-4108-a7e9-5ba9b8fa2991)

**Comment by FStriewski** [comment]
Seems fixed, closed for now.
