### ISSUE TITLE
[frontend] fix margin of row titles and service details

### ISSUE THREAD

**Issue by fionatiefenbacher** [FHNW-IVGI/Geoharvester#63]
The alignment of the row titles is centered, wheres the abstract and the dropdown service details are left aligned. Fix both to left with same margin, so that the details align to the titles and abstracts.

![grafik](https://github.com/FHNW-IVGI/Geoharvester/assets/93774586/9edf1356-722f-4223-b6db-a58a3c6e2f96)

**Comment by fionatiefenbacher** [comment]
After further testing, the margin/padding of the service rows and service table changes during searching for different querys and applying filters. This needs fixing, so that the table is static instead of dynamic. Subrows (Details) of services are static.

- [ ] static Service Table, when applying different querys
- [ ] static Service Rows, so that it aligns with their details below

**Comment by FStriewski** [comment]
Fixed in https://github.com/FHNW-IVGI/Geoharvester/pull/68
