### ISSUE TITLE
[frontend] opened service row at index stays open at this index when applying new query

### ISSUE THREAD

**Issue by fionatiefenbacher** [FHNW-IVGI/Geoharvester#64]
The index for the opened service row to reveal the metadata comes in to the next query and stays open, but should be set to all close. 

query nr 1 with, index 1 open

![grafik](https://github.com/FHNW-IVGI/Geoharvester/assets/93774586/b62b10d3-fa6e-4100-8c4a-93cbf869cf7f)

query nr 2 (applied filter), index 1 open but should be closed

![grafik](https://github.com/FHNW-IVGI/Geoharvester/assets/93774586/198d9b17-8208-49b6-85a1-4fa0effb8334)

images also show the issue #63 with the dynamic table, which should be static.

**Comment by FStriewski** [comment]
Fixed in https://github.com/FHNW-IVGI/Geoharvester/pull/68
