### ISSUE TITLE
Enhance csv ingestion with preloading data on startup event

### ISSUE THREAD

**Issue by FStriewski** [FHNW-IVGI/Geoharvester#7]
Enhancement to https://github.com/FHNW-IVGI/Geoharvester/issues/4 :

Use FastApis "Startup Event" to preload the data into the dataframe, then run searches on cached dataframe. Evaluate if this reduces the response times sufficently for testing & further development.
See: https://fastapi.tiangolo.com/advanced/events/

Possible outcomes:
**+** : Continue with explorative approach and new features, decide on database / datastore later
**-** :  Prioritize database or interim solution (e.g. in-memory databases like redis) over new features

**Comment by davidoesch** [comment]
https://duckdb.org might be an option

**Comment by FStriewski** [comment]
Implemented with https://github.com/FHNW-IVGI/Geoharvester/pull/8.
There is some gain in performance, which should be good enough for development and testing.
Still for now the search runs across all rows (title and abstract columns) which takes some time.
