### ISSUE TITLE
[Frontend] - Metadata quality icon no more available

### ISSUE THREAD

**Issue by p1d1d1** [FHNW-IVGI/Geoharvester#78]
As in the title. Please fix

**Comment by FStriewski** [comment]
Thanks for reporting. We didn`t have any code changes on this part lately, but it is a problem we encountered before. We`ll have a look.

**Comment by eliaferrari** [comment]
The data are now preprocessed and loaded in redis correctly in the branche **main_preprocessing**.
However, I still have a problem with the pagination on my local machine, maybe @FStriewski we can have a look at it together.

**Comment by FStriewski** [comment]
I`ve deployed your branch to the server @eliaferrari  and the metadata is coming trough. Let`s see how it looks like tomorrow, to check if it still runs fine after the scraper has run. 

Pagination also still seems to work and the sorting seems correct to me

**Comment by FStriewski** [comment]
Current main fails because of a pydantic error, that I can`t replicate on localhost. Maybe due to version differences or a cached .csv somewhere? I'll have a look but probably tomorrow 

![image](https://github.com/FHNW-IVGI/Geoharvester/assets/36440175/07cad30c-14f2-4cf7-b1dc-d0c774c23f54)

**Comment by FStriewski** [comment]
Not sure what the real reason behind this is but if we remove "lang2" and "update" fields from the schema it runs fine. Both fields are optional, so I`m not sure why it gets hung up on that. The type is correct and we have more optional fields, so the issue must be on the csv or pickle side and some changes there.

app/redis/schema.py:
![image](https://github.com/FHNW-IVGI/Geoharvester/assets/36440175/4cdd33bf-f0f1-49d8-8768-cf5b764e2f62)

**Comment by eliaferrari** [comment]
I've just updated the main_preprocessing branch. The problem with pydantic is now resolved removing the two fields (update and lang_2).
I've also created a temporary Pickle dataframe in main branch, which will be overwritten from the next scraper run.
If there are no more open matters on this issue and the branch works on the server I'll merge the main_preprocessing definitely.

**Comment by FStriewski** [comment]
Thanks for seeing into it @eliaferrari 👍 I`ve deployed your changes to prod and it looks very promising!
Ì'd say go ahead and merge to main.
